- .circleci/config.yml
- .github/chart-testing.yaml
- .github/helm-docs.sh
- .github/kubeval.sh
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .helm/bridgeconnector/.helmignore
- .helm/bridgeconnector/Chart.yaml
- .helm/bridgeconnector/README.md.gotmpl
- .helm/bridgeconnector/templates/NOTES.txt
- .helm/bridgeconnector/templates/_helpers.tpl
- .helm/bridgeconnector/templates/configmap.yaml
- .helm/bridgeconnector/templates/deployment.yaml
- .helm/bridgeconnector/templates/secret.yaml
- .helm/bridgeconnector/templates/service.yaml
- .helm/bridgeconnector/values.yaml
- package.json
* Add Helm charts and templates
* Add GitHub actions configurations to test these charts
> [CHORE] Add GitHub actions to test Helm charts 

- package-lock.json
- package.json
- src/aggregator/services/aggregator.service.spec.ts
- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/bridge/bridge.client.spec.ts
- src/aggregator/services/bridge/bridge.client.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- Ability to add an email if it is defined to skip the email page
> feat(bridge.client): add a prefilled email if it is defined

- package-lock.json
- package.json
- src/aggregator/interfaces/bridge.interface.ts
- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/bridge/bridge.client.spec.ts
- src/algoan/algoan.service.spec.ts
- src/algoan/algoan.service.ts
- src/app.controller.ts
- src/hooks/controllers/hooks.controller.ts
- src/hooks/services/hooks.service.ts
- src/main.ts
- test/utils/app.ts
- tsconfig.json
- Upgrade `@algoan/eslint-config` and activate the typescript `strictNullChecks` option
- Correct all build and lint issue
> [FIX] Upgrade ESLint and active "strictNullChecks" options

- config/default.json
- src/hooks/services/hooks.service.ts
- Fix wrong condition for stopping the synchronisation
- Set new default values
> [FIX] Wrong condition on transactions synchronisation 

- src/aggregator/services/bridge/bridge.client.ts
Add the error data in the logs
> [FEAT]: enhance bridge error logs

- src/aggregator/services/aggregator.service.spec.ts
- src/aggregator/services/aggregator.service.ts
- Fix do not throw on conflict user already exists
The goal of this fix is to allow a user to do multiple aggregation. Currently when the same user tries to do to aggregation (typically with two different banks), it throws the error 409 Conflict.
> [FIX] Fix do not throw on conflict user already exists

- config/default.json
- src/aggregator/services/bridge/bridge.client.ts
- Ability to enable/disable logs for Bridge requests
- Improves log messages and add a log if there is a successful request
> feat(bridge-client): ability to disable logs for Bridge requests

- src/hooks/controllers/hooks.controller.spec.ts
- src/hooks/dto/aggregator-link-required.dto.ts
- src/hooks/dto/event.dto.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- Add an event handler for `aggregator_link_required`
> [FEAT] Add event handler for `aggregator_link_required`

- config/env/test.json
- src/aggregator/services/bridge/bridge-v2.utils.spec.ts
- src/aggregator/services/bridge/bridge-v2.utils.ts
- src/algoan/dto/analysis.inputs.ts
- src/hooks/dto/bank-details-required.dto.ts
- src/hooks/dto/event.dto.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- Add an event handler for `bank_details_required`
> [FEAT] Add event handler for `bank_details_required`

- src/algoan/dto/analysis.enum.ts
- src/algoan/dto/analysis.inputs.ts
- src/algoan/dto/analysis.objects.ts
- src/hooks/services/hooks.service.ts
Update the analysis's status and error when encountering an error during fetching data from the aggregator
> Update analysis error when handling `bankDetailsRequired` event

- src/aggregator/services/aggregator.service.spec.ts
- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/bridge/bridge.client.ts
- Append the context to the redirectUrl only if defined (since it is an optional parameter)
- Fix the check on the 409 error
https://docs.bridgeapi.io/reference#connect-an-item
> [FIX] Fix the fetching redirectUrl process

- Dockerfile
- config/default.json
- package-lock.json
- src/aggregator/services/bridge/bridge.client.spec.ts
- Move package-lock to v2
- Change the Bridge default URL
- Change the Docker version to fermium
> [FIX]: Bridge URL and Docker version

- config/default.json
- package-lock.json
- src/aggregator/services/bridge/bridge.client.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
To allow Algoan Connect to be used several times for the same user, we should remove the deletion of the user from Bridge.  Moreover, the user is automatically removed by Bridge after a certain period. 
EDIT (23/05): create a new config to delete users
> fix(hooks): remove the user deletion from Bridge

- src/aggregator/services/bridge/bridge.client.spec.ts
- src/aggregator/services/bridge/bridge.client.ts
- Clean the context when adding item if it contains special characters 
- Do not send the context if it is empty
> [FIX] Clean context

- src/aggregator/services/bridge/bridge-v2.utils.spec.ts
- src/aggregator/services/bridge/bridge-v2.utils.ts
- Add mapping to UNKNOWN for non mapped account types
> [FIX] Add default account mapping

- .vscode/settings.json
- src/aggregator/interfaces/bridge-mock.ts
- src/aggregator/interfaces/bridge.interface.ts
- src/aggregator/services/aggregator.service.spec.ts
- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/bridge/bridge-v2.utils.spec.ts
- src/aggregator/services/bridge/bridge-v2.utils.ts
- src/aggregator/services/bridge/bridge.client.spec.ts
- src/aggregator/services/bridge/bridge.client.ts
- src/hooks/services/hooks.service.ts
Add `v2/accounts-information` api call to get the owner information to fix the owner name not showing.
> [FIX] Fix account owner information not showing

- src/aggregator/services/bridge/bridge.client.spec.ts
- src/aggregator/services/bridge/bridge.client.ts
fix response format of the /accounts-information call
> [FIX] fix response format

- src/aggregator/interfaces/bridge-mock.ts
- src/aggregator/services/aggregator.service.spec.ts
- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/bridge/bridge-v2.utils.spec.ts
- src/aggregator/services/bridge/bridge-v2.utils.ts
- src/aggregator/services/bridge/bridge.client.spec.ts
- src/aggregator/services/bridge/bridge.client.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- Remove deprecated /kyc route
- fix fetching account info by accountId instead of item id
> [FIX] fix fetching owner

- src/hooks/services/hooks.service.ts
Do not delete user if account informations not fetched for debug purpose. 
This is temporary
> [FEAT] do not delete user if account informations not fetched

- config/default.json
- config/env/test.json
- json-server/server.js
- src/algoan/algoan.module.ts
- src/algoan/interfaces/index.ts
- src/algoan/interfaces/paginated-data.ts
- src/algoan/services/algoan-http.service.ts
- src/algoan/services/algoan-service-account.service.ts
- src/algoan/services/algoan.service.spec.ts
- src/algoan/services/algoan.service.ts
- src/app.controller.spec.ts
- src/hooks/controllers/hooks.controller.spec.ts
- src/hooks/dto/event.dto.ts
- src/hooks/dto/service-account-updated.dto.ts
- src/hooks/dto/subscription.dto.ts
- src/hooks/enums/event-name.enum.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- test/utils/app.ts
Use /v2/service-accounts instead of v2/service-accounts which is deprecated and soon will be removed from Algoan server
> [FEAT] use v2 to fetch service-accounts
